//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaristaLabs.Skrapr.Common.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaristaLabs.Skrapr.Common.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Weather Comparison&quot;,
        ///  &quot;description&quot;: &quot;Skrapes numerous weather sources to compare the results.&quot;,
        ///  &quot;skraprs&quot;: [
        ///    {
        ///      &quot;type&quot;: &quot;web&quot;,
        ///      &quot;name&quot;: &quot;Weather.com&quot;,
        ///      &quot;description&quot;: &quot;Gets weather information from weather.com&quot;,
        ///      &quot;userAgent&quot;: &quot;Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko&quot;,
        ///      &quot;startUrls&quot;: [
        ///        &quot;http://www.weather.com/&quot;
        ///      ],
        ///      &quot;includeFilter&quot;: [
        ///        &quot;http://www.weather.com/.*&quot;
        ///      ],
        ///      &quot;ignoreRobots&quot;: true,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleProject01 {
            get {
                return ResourceManager.GetString("ExampleProject01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;web&quot;,
        ///  &quot;name&quot;: &quot;Weather.com&quot;,
        ///  &quot;description&quot;: &quot;Gets weather information from weather.com&quot;,
        ///  &quot;userAgent&quot;: &quot;Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko&quot;,
        ///  &quot;startUrls&quot;: [
        ///    &quot;http://www.weather.com/&quot;
        ///  ],
        ///  &quot;includeFilter&quot;: [
        ///    &quot;http://www.weather.com/.*&quot;
        ///  ],
        ///  &quot;ignoreRobots&quot;: true,
        ///  &quot;authenticators&quot;: [
        ///    {
        ///      &quot;type&quot;: &quot;ntlm&quot;,
        ///      &quot;username&quot;: &quot;testuser&quot;,
        ///      &quot;password&quot;: &quot;password&quot;
        ///    },
        ///    {
        ///      &quot;type&quot;: &quot;form&quot;,
        ///      &quot;requireJQuery&quot;: true, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleSkrapr01 {
            get {
                return ResourceManager.GetString("ExampleSkrapr01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Front Page Weather&quot;,
        ///  &quot;description&quot;: &quot;Gets the weather information from the front page.&quot;,
        ///  &quot;pattern&quot;: {
        ///    &quot;url&quot;: &quot;http://www.weather.com/weather/today/\\d{5}&quot;,
        ///    &quot;mimeType&quot;: &quot;text/html&quot;
        ///  },
        ///  &quot;type&quot;: &quot;Weather&quot;,
        ///  &quot;requireJQuery&quot;: true,
        ///  &quot;properties&quot;: {
        ///    &quot;source&quot;: {
        ///      &quot;type&quot;: &quot;const&quot;,
        ///      &quot;value&quot;: &quot;Weather.com&quot;
        ///    },
        ///    &quot;zipCode&quot;: {
        ///      &quot;type&quot;: &quot;lastPathSegment&quot;,
        ///      &quot;valueType&quot;: &quot;PrimaryKey&quot;
        ///    },
        ///    &quot;url&quot;: {
        ///      &quot;type&quot;: &quot;url&quot;
        ///    },
        ///    &quot;retrieve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleTarget01 {
            get {
                return ResourceManager.GetString("ExampleTarget01", resourceCulture);
            }
        }
    }
}
